package relational

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sync"
	"testing"
	"time"

	kitdbengine "github.com/kitwork/engine/kitdb"
	kitdbsql "github.com/kitwork/engine/kitdb/sql"
)

func TestIdentityInsertDefaultsAndSession(t *testing.T) {
	e := bigintTestEngine(t)
	s := e.NewSession()
	ctx := context.Background()
	before, _ := e.database.LastTransaction()
	sequenceQuery(t, s, `CREATE TABLE orders (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, cost BIGINT DEFAULT 10)`)
	after, _ := e.database.LastTransaction()
	if after != before+1 {
		t.Fatalf("table and sequence did not publish together: %d -> %d", before, after)
	}
	if _, err := e.Describe(ctx, `INSERT INTO orders(name) VALUES ($1) RETURNING id`); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Execute(ctx, `SELECT currval('orders_id_seq')`); err == nil {
		t.Fatal("Describe reserved an ID")
	}
	sequenceQuery(t, s, `INSERT INTO orders(name) VALUES ('one') RETURNING id,cost`, int64(1), int64(10))
	sequenceQuery(t, s, `SELECT currval('orders_id_seq'),lastval()`, int64(1), int64(1))
	r, err := s.Execute(ctx, `INSERT INTO orders(id,name,cost) VALUES (DEFAULT,'two',DEFAULT),(DEFAULT,'three',25) RETURNING id,cost`)
	if err != nil || !reflect.DeepEqual(r.Rows, [][]any{{int64(2), int64(10)}, {int64(3), int64(25)}}) {
		t.Fatalf("multi: %#v %v", r, err)
	}
	sequenceQuery(t, s, `INSERT INTO orders(id,name) VALUES (99,'manual') RETURNING id`, int64(99))
	sequenceQuery(t, s, `SELECT currval('orders_id_seq')`, int64(3))
	if _, err := s.Execute(ctx, `INSERT INTO orders(id,name) VALUES (NULL,'bad')`); err == nil {
		t.Fatal("explicit NULL became a generated ID")
	}
	tx, err := s.BeginTransaction(ctx, TransactionOptions{})
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	sequenceQuery(t, tx, `INSERT INTO orders(name) VALUES ('rollback') RETURNING id`, int64(4))
	if err := tx.Rollback(); err != nil {
		t.Fatal(err)
	}
	sequenceQuery(t, s, `SELECT currval('orders_id_seq')`, int64(4))
	sequenceQuery(t, s, `INSERT INTO orders(name) VALUES ('after') RETURNING id`, int64(5))
	// A constraint failure rolls back every row but never reclaims reservations.
	if _, err := s.Execute(ctx, `INSERT INTO orders(id,name) VALUES (DEFAULT,'not saved'),(99,'duplicate')`); err == nil {
		t.Fatal("duplicate accepted")
	}
	sequenceQuery(t, s, `SELECT COUNT(*) FROM orders`, int64(5))
	sequenceQuery(t, s, `INSERT INTO orders(name) VALUES ('gap') RETURNING id`, int64(7))
	sequenceQuery(t, s, `UPDATE orders SET cost=DEFAULT WHERE id=2 RETURNING cost`, int64(10))
	sequenceQuery(t, s, `CREATE SEQUENCE shared START 100`)
	sequenceQuery(t, s, `CREATE TABLE shared_ids (id BIGINT PRIMARY KEY DEFAULT nextval('shared'))`)
	sequenceQuery(t, s, `INSERT INTO shared_ids DEFAULT VALUES RETURNING id`, int64(100))
	if _, err := s.Execute(ctx, `DROP SEQUENCE shared`); err == nil {
		t.Fatal("dropped referenced default")
	}
	sequenceQuery(t, s, `DROP TABLE shared_ids`)
	sequenceQuery(t, s, `SELECT nextval('shared')`, int64(101))
	sequenceQuery(t, s, `DROP SEQUENCE shared`)
}

func TestIdentityAlwaysOverridesAndUpdate(t *testing.T) {
	e := bigintTestEngine(t)
	s := e.NewSession()
	ctx := context.Background()
	sequenceQuery(t, s, `CREATE TABLE always_ids (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT)`)
	sequenceQuery(t, s, `INSERT INTO always_ids(name) VALUES ('one') RETURNING id`, int64(1))
	for _, source := range []string{
		`INSERT INTO always_ids(id) VALUES (9)`, `INSERT INTO always_ids(id) VALUES (NULL)`,
		`INSERT INTO always_ids(id,name) VALUES (DEFAULT,'not saved'),(8,'bad')`,
	} {
		if _, err := s.Execute(ctx, source); err == nil {
			t.Fatalf("accepted %s", source)
		}
	}
	sequenceQuery(t, s, `SELECT COUNT(*) FROM always_ids`, int64(1))
	sequenceQuery(t, s, `INSERT INTO always_ids(id) OVERRIDING SYSTEM VALUE VALUES (99) RETURNING id`, int64(99))
	// The failed two-row statement may have consumed a value before rejecting row 2.
	r, err := s.Execute(ctx, `INSERT INTO always_ids(id) OVERRIDING USER VALUE VALUES (999) RETURNING id`)
	if err != nil || r.Rows[0][0] == int64(999) {
		t.Fatalf("user override %#v %v", r, err)
	}
	sequenceQuery(t, s, `CREATE TABLE events (id BIGINT PRIMARY KEY, number BIGINT GENERATED ALWAYS AS IDENTITY, manual BIGINT GENERATED BY DEFAULT AS IDENTITY)`)
	sequenceQuery(t, s, `INSERT INTO events(id,manual) VALUES (1,500) RETURNING number,manual`, int64(1), int64(500))
	if _, err := s.Execute(ctx, `UPDATE events SET number=9 WHERE id=1`); err == nil {
		t.Fatal("updated ALWAYS explicitly")
	}
	sequenceQuery(t, s, `UPDATE events SET number=DEFAULT,manual=DEFAULT WHERE id=1 RETURNING number,manual`, int64(2), int64(1))
	sequenceQuery(t, s, `UPDATE events SET manual=99 WHERE id=1 RETURNING manual`, int64(99))
	sequenceQuery(t, s, `INSERT INTO events(id,manual) OVERRIDING USER VALUE VALUES (2,555) RETURNING number,manual`, int64(3), int64(2))
	if _, err := s.Execute(ctx, `INSERT INTO events(id,manual) VALUES (3,NULL)`); err == nil {
		t.Fatal("identity accepted NULL")
	}
}

func TestIdentityOwnershipRenameDropAndAtomicFailure(t *testing.T) {
	e := bigintTestEngine(t)
	s := e.NewSession()
	ctx := context.Background()
	for _, source := range []string{
		`CREATE TABLE bad (id BIGSERIAL PRIMARY KEY, parent BIGINT REFERENCES missing(id))`,
		`CREATE TABLE bad (id BIGSERIAL PRIMARY KEY DEFAULT 9)`,
		`CREATE TABLE bad (id BIGINT GENERATED ALWAYS AS IDENTITY NULL PRIMARY KEY)`,
		`CREATE TABLE bad (id BIGINT DEFAULT 5 GENERATED ALWAYS AS IDENTITY PRIMARY KEY)`,
		`CREATE TABLE bad (id TEXT GENERATED ALWAYS AS IDENTITY PRIMARY KEY)`,
	} {
		if _, err := s.Execute(ctx, source); err == nil {
			t.Fatalf("accepted %s", source)
		}
	}
	catalog, err := e.database.Catalog()
	if err != nil || len(catalog.Structs) != 0 || len(catalog.Sequences) != 0 {
		t.Fatalf("failed CREATE leaked catalog: %+v %v", catalog, err)
	}
	sequenceQuery(t, s, `CREATE SEQUENCE records_number_seq START 10`)
	sequenceQuery(t, s, `CREATE TABLE records (id BIGINT PRIMARY KEY, number BIGSERIAL)`)
	sequenceQuery(t, s, `INSERT INTO records(id) VALUES (1) RETURNING number`, int64(1))
	sequenceQuery(t, s, `SELECT currval('records_number_seq_2')`, int64(1))
	sequenceQuery(t, s, `ALTER TABLE records RENAME COLUMN number TO ticket`)
	sequenceQuery(t, s, `ALTER TABLE records RENAME TO renamed`)
	sequenceQuery(t, s, `INSERT INTO renamed(id) VALUES (2) RETURNING ticket`, int64(2))
	if _, err := s.Execute(ctx, `DROP SEQUENCE records_number_seq_2`); err == nil {
		t.Fatal("dropped owned sequence")
	}
	sequenceQuery(t, s, `CREATE TABLE dependent (id BIGINT PRIMARY KEY DEFAULT nextval('records_number_seq_2'))`)
	if _, err := s.Execute(ctx, `ALTER TABLE renamed DROP COLUMN ticket`); err == nil {
		t.Fatal("dropped externally referenced owner column")
	}
	if _, err := s.Execute(ctx, `DROP TABLE renamed`); err == nil {
		t.Fatal("dropped externally referenced owner table")
	}
	sequenceQuery(t, s, `DROP TABLE dependent`)
	sequenceQuery(t, s, `ALTER TABLE renamed DROP COLUMN ticket`)
	if _, err := e.database.SequenceByName("records_number_seq_2"); !errors.Is(err, kitdbengine.ErrSequenceNotFound) {
		t.Fatal(err)
	}
	sequenceQuery(t, s, `SELECT nextval('records_number_seq')`, int64(10))
	sequenceQuery(t, s, `DROP TABLE renamed`)
	sequenceQuery(t, s, `CREATE TABLE records (id BIGSERIAL PRIMARY KEY)`)
	sequenceQuery(t, s, `INSERT INTO records DEFAULT VALUES RETURNING id`, int64(1))
	sequenceQuery(t, s, `DROP TABLE records`)
	sequenceQuery(t, s, `CREATE TABLE records (id BIGSERIAL PRIMARY KEY)`)
	if _, err := s.Execute(ctx, `SELECT currval('records_id_seq')`); err == nil {
		t.Fatal("recreated identity inherited session value")
	}
	sequenceQuery(t, s, `INSERT INTO records DEFAULT VALUES RETURNING id`, int64(1))
	sequenceQuery(t, s, `CREATE TABLE legacy (id INTEGER PRIMARY KEY)`)
	catalog, _ = e.database.Catalog()
	for _, entry := range catalog.Structs {
		if entry.Name == "legacy" && entry.Version != kitdbsql.SchemaVersion2 {
			t.Fatal("ordinary schema was unnecessarily upgraded")
		}
		if entry.Name == "records" && entry.Version != kitdbsql.SchemaVersion3 {
			t.Fatal("identity schema lacks version gate")
		}
	}
}

func TestIdentityConcurrentInsert(t *testing.T) {
	e := bigintTestEngine(t)
	sequenceQuery(t, e, `CREATE TABLE tickets (id BIGSERIAL PRIMARY KEY, payload TEXT)`)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	const workers, count = 6, 8
	results := make(chan int64, workers*count)
	errorsCh := make(chan error, workers)
	var wait sync.WaitGroup
	for range workers {
		wait.Go(func() {
			s := e.NewSession()
			for range count {
				for attempt := 0; ; attempt++ {
					r, err := s.Execute(ctx, `INSERT INTO tickets(payload) VALUES ('issued') RETURNING id`)
					if errors.Is(err, ErrTransactionConflict) && attempt < 50 {
						continue
					}
					if err != nil {
						errorsCh <- err
						return
					}
					results <- r.Rows[0][0].(int64)
					break
				}
			}
		})
	}
	wait.Wait()
	close(results)
	close(errorsCh)
	for err := range errorsCh {
		t.Fatal(err)
	}
	seen := map[int64]bool{}
	for id := range results {
		if id <= 0 || seen[id] {
			t.Fatalf("duplicate generated ID: %d", id)
		}
		seen[id] = true
	}
	if len(seen) != workers*count {
		t.Fatal(len(seen))
	}
	sequenceQuery(t, e, `SELECT COUNT(*) FROM tickets`, int64(workers*count))
}

func TestIdentityCacheReopenAndCommitReduction(t *testing.T) {
	path := filepath.Join(t.TempDir(), "identity-cache.kitdb")
	e, err := Open(path)
	if err != nil {
		t.Fatal(err)
	}
	sequenceQuery(t, e, `CREATE TABLE cached (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 4) PRIMARY KEY, label TEXT)`)
	before, err := e.database.Stats()
	if err != nil {
		t.Fatal(err)
	}
	sequenceQuery(t, e, `INSERT INTO cached(label) VALUES ('one') RETURNING id`, int64(1))
	sequenceQuery(t, e, `INSERT INTO cached(label) VALUES ('two') RETURNING id`, int64(2))
	after, err := e.database.Stats()
	if err != nil {
		t.Fatal(err)
	}
	if after.CommittedTransactions-before.CommittedTransactions != 3 {
		t.Fatalf("two rows used %d commits, want one lease plus two rows", after.CommittedTransactions-before.CommittedTransactions)
	}
	if err := e.Close(); err != nil {
		t.Fatal(err)
	}
	e, err = Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer e.Close()
	sequenceQuery(t, e, `INSERT INTO cached(label) VALUES ('after reopen') RETURNING id`, int64(5))
	sequenceQuery(t, e, `SELECT COUNT(*) FROM cached`, int64(3))
}

func TestIdentityKernelDependencyGuard(t *testing.T) {
	e := bigintTestEngine(t)
	sequenceQuery(t, e, `CREATE TABLE tickets (id BIGSERIAL PRIMARY KEY)`)
	catalog, err := e.database.Catalog()
	if err != nil {
		t.Fatal(err)
	}
	for _, dropOwner := range []bool{false, true} {
		tx, err := e.database.Begin()
		if err != nil {
			t.Fatal(err)
		}
		if dropOwner {
			err = tx.DeleteStruct(catalog.Structs[0].ID)
		} else {
			err = tx.DropSequence(catalog.Sequences[0].ID)
		}
		if err == nil {
			_, err = tx.CommitSequenceChanges()
		}
		_ = tx.Rollback()
		if !errors.Is(err, kitdbengine.ErrInvalidCatalog) {
			t.Fatalf("partial dependency deletion: %v", err)
		}
		after, err := e.database.Catalog()
		if err != nil || after.Transaction != catalog.Transaction || after.Revision != catalog.Revision {
			t.Fatalf("rejected catalog commit published state: %+v %v", after, err)
		}
	}
	sequenceQuery(t, e, `INSERT INTO tickets DEFAULT VALUES RETURNING id`, int64(1))
}

func TestIdentityStatementSavepointAndReadOnly(t *testing.T) {
	e := bigintTestEngine(t)
	s := e.NewSession()
	ctx := context.Background()
	sequenceQuery(t, s, `CREATE TABLE tickets (id BIGSERIAL PRIMARY KEY, label TEXT UNIQUE)`)
	readOnly, err := s.BeginTransaction(ctx, TransactionOptions{ReadOnly: true})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := readOnly.Execute(ctx, `INSERT INTO tickets DEFAULT VALUES`); err == nil {
		t.Fatal("read-only generated an identity")
	}
	_ = readOnly.Rollback()
	if _, err := s.Execute(ctx, `SELECT currval('tickets_id_seq')`); err == nil {
		t.Fatal("read-only write consumed a reservation")
	}
	tx, err := s.BeginTransaction(ctx, TransactionOptions{})
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	sequenceQuery(t, tx, `INSERT INTO tickets(label) VALUES ('kept') RETURNING id`, int64(1))
	if _, err := tx.Execute(ctx, `INSERT INTO tickets(label) VALUES ('discarded'),('kept')`); err == nil {
		t.Fatal("duplicate UNIQUE value accepted")
	}
	sequenceQuery(t, tx, `SELECT COUNT(*) FROM tickets`, int64(1))
	sequenceQuery(t, tx, `SELECT currval('tickets_id_seq')`, int64(3))
	sequenceQuery(t, tx, `INSERT INTO tickets(label) VALUES ('after') RETURNING id`, int64(4))
	if _, err := tx.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	sequenceQuery(t, s, `SELECT COUNT(*) FROM tickets`, int64(2))
	sequenceQuery(t, s, `SELECT COUNT(*) FROM tickets WHERE label='discarded'`, int64(0))
}

func TestIdentityCrashRecovery(t *testing.T) {
	if path := os.Getenv("KITDB_IDENTITY_CRASH_CHILD"); path != "" {
		phase := os.Getenv("KITDB_IDENTITY_CRASH_PHASE")
		e, err := Open(path)
		if err != nil {
			t.Fatal(err)
		}
		_, err = e.database.AddCommitListener(func(event kitdbengine.CommitEvent) {
			table, counter, row, drop := false, false, false, false
			for _, op := range event.Operations {
				if len(op.Key) == 17 && op.Key[0] == 0x01 {
					table = true
					drop = op.Kind == kitdbengine.CommitOperationDelete
				}
				counter = counter || len(op.Key) == 17 && op.Key[0] == 0x02
				row = row || len(op.Key) > 0 && op.Key[0] == 0x10
			}
			if phase == "table" && table && !drop || phase == "allocation" && counter && !table || phase == "row" && row || phase == "drop" && table && drop {
				os.Exit(44)
			}
		})
		if err != nil {
			t.Fatal(err)
		}
		sequenceQuery(t, e, `CREATE TABLE orders (id BIGSERIAL PRIMARY KEY)`)
		sequenceQuery(t, e, `INSERT INTO orders DEFAULT VALUES RETURNING id`, int64(1))
		sequenceQuery(t, e, `DROP TABLE orders`)
		t.Fatal("crash boundary not reached")
	}
	for _, phase := range []string{"table", "allocation", "row", "drop"} {
		t.Run(phase, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "crash.kitdb")
			child := exec.Command(os.Args[0], "-test.run=^TestIdentityCrashRecovery$")
			child.Env = append(os.Environ(), "KITDB_IDENTITY_CRASH_CHILD="+path, "KITDB_IDENTITY_CRASH_PHASE="+phase)
			output, err := child.CombinedOutput()
			if exit, ok := err.(*exec.ExitError); !ok || exit.ExitCode() != 44 {
				t.Fatalf("child: %v %s", err, output)
			}
			e, err := Open(path)
			if err != nil {
				t.Fatal(err)
			}
			defer e.Close()
			catalog, err := e.database.Catalog()
			if err != nil {
				t.Fatal(err)
			}
			if phase == "drop" {
				if len(catalog.Structs) != 0 || len(catalog.Sequences) != 0 {
					t.Fatalf("drop leaked: %+v", catalog)
				}
				return
			}
			if len(catalog.Structs) != 1 || len(catalog.Sequences) != 1 {
				t.Fatalf("partial CREATE: %+v", catalog)
			}
			rows, next := int64(0), int64(2)
			if phase == "table" {
				next = 1
			}
			if phase == "row" {
				rows = 1
			}
			sequenceQuery(t, e, `SELECT COUNT(*) FROM orders`, rows)
			sequenceQuery(t, e, `INSERT INTO orders DEFAULT VALUES RETURNING id`, next)
			anchor := filepath.Join(t.TempDir(), "backup.kitdb")
			if _, err := e.database.CreateBackupAnchor(context.Background(), anchor); err != nil {
				t.Fatal(err)
			}
			backup, err := Open(anchor)
			if err != nil {
				t.Fatal(err)
			}
			defer backup.Close()
			sequenceQuery(t, backup, `INSERT INTO orders DEFAULT VALUES RETURNING id`, next+1)
		})
	}
}

func TestIdentityPostgresWireMetadata(t *testing.T) {
	e := bigintTestEngine(t)
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan error, 1)
	go func() {
		done <- e.ServePostgres(ctx, listener, PostgresServerOptions{PostgresOptions: PostgresOptions{Database: "identity", User: "kitdb", Password: "test-only"}})
	}()
	t.Cleanup(func() {
		cancel()
		select {
		case err := <-done:
			if err != nil {
				t.Error(err)
			}
		case <-time.After(5 * time.Second):
			t.Error("server did not stop")
		}
	})
	db, err := sql.Open("postgres", fmt.Sprintf("postgres://kitdb:test-only@%s/identity?sslmode=disable", listener.Addr()))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	connection, err := db.Conn(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer connection.Close()
	if _, err := connection.ExecContext(ctx, `CREATE TABLE products (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 32) PRIMARY KEY, name TEXT)`); err != nil {
		t.Fatal(err)
	}
	statement, err := connection.PrepareContext(ctx, `INSERT INTO products(name) VALUES ($1) RETURNING id`)
	if err != nil {
		t.Fatal(err)
	}
	defer statement.Close()
	var id int64
	if err := statement.QueryRowContext(ctx, "first").Scan(&id); err != nil || id != 1 {
		t.Fatalf("prepared: %d %v", id, err)
	}
	if err := connection.QueryRowContext(ctx, `SELECT currval('products_id_seq')`).Scan(&id); err != nil || id != 1 {
		t.Fatalf("currval: %d %v", id, err)
	}
	var identity, generation, start string
	if err := connection.QueryRowContext(ctx, `SELECT is_identity,identity_generation,identity_start FROM information_schema.columns WHERE table_name='products' AND column_name='id'`).Scan(&identity, &generation, &start); err != nil || identity != "YES" || generation != "ALWAYS" || start != "1" {
		t.Fatalf("identity metadata: %q %q %q %v", identity, generation, start, err)
	}
	var mode string
	if err := connection.QueryRowContext(ctx, `SELECT attidentity FROM pg_catalog.pg_attribute WHERE attname='id'`).Scan(&mode); err != nil || mode != "a" {
		t.Fatalf("attidentity: %q %v", mode, err)
	}
	var cache int64
	if err := connection.QueryRowContext(ctx, `SELECT seqcache FROM pg_catalog.pg_sequence`).Scan(&cache); err != nil || cache != 32 {
		t.Fatalf("seqcache: %d %v", cache, err)
	}
	tx, err := connection.BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := tx.QueryRow(`INSERT INTO products(name) VALUES ('rollback') RETURNING id`).Scan(&id); err != nil || id != 2 {
		t.Fatalf("tx: %d %v", id, err)
	}
	if err := tx.Rollback(); err != nil {
		t.Fatal(err)
	}
	if err := statement.QueryRowContext(ctx, "after").Scan(&id); err != nil || id != 3 {
		t.Fatalf("rollback reclaimed ID: %d %v", id, err)
	}
}
