package compiler

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"

	
	"github.com/kitwork/engine/runtime"
	"github.com/kitwork/engine/value"
)

// Adversarial closure scenarios (generated by a multi-agent design pass, stored in
// testdata/closure_scenarios.json) stress the VM closure-capture fix: deep scope
// chains, recursion, mutation, fan-out, iteration, heavy frame-slot churn.

type closureScenario struct {
	Name       string  `json:"name"`
	JS         string  `json:"js"`
	ExpectKind string  `json:"expectKind"`
	ExpectNum  float64 `json:"expectNum"`
	ExpectBool bool    `json:"expectBool"`
	ExpectStr  string  `json:"expectStr"`
	Rationale  string  `json:"rationale"`
	Area       string  `json:"area"`
}

// tryRun compiles + runs a single-file script and returns its top-level `result`,
// turning parse/compile/runtime errors and panics into a returned error (non-fatal).
func tryRun(src string) (res value.Value, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic: %v", r)
		}
	}()
	prog, perr := parseProgram(src)
	if perr != nil {
		return value.Value{}, fmt.Errorf("parse: %w", perr)
	}
	c := NewCompiler(src)
	if cerr := c.Compile(prog); cerr != nil {
		return value.Value{}, fmt.Errorf("compile: %w", cerr)
	}
	bc := c.ByteCodeResult()
	vm := runtime.New(bc.Instructions, bc.Constants)
	vm.SourceMap = bc.SourceMap
	vm.MaxEnergy = 100_000_000
	out := vm.Run()
	if out.K == value.Invalid {
		return value.Value{}, fmt.Errorf("runtime: %v", out.V)
	}
	return vm.Vars["result"], nil
}

func TestClosureAdversarialScenarios(t *testing.T) {
	data, err := os.ReadFile("testdata/closure_scenarios.json")
	if err != nil {
		t.Fatal(err)
	}
	var out struct {
		Result struct {
			Scenarios []closureScenario `json:"scenarios"`
		} `json:"result"`
	}
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatal(err)
	}
	scn := out.Result.Scenarios
	if len(scn) == 0 {
		t.Fatal("no scenarios loaded")
	}

	var pass, skipped, wrong int
	for _, s := range scn {
		got, runErr := tryRun(s.JS)
		if runErr != nil {
			// parse/compile error → almost certainly the scenario used syntax outside
			// the Kitwork subset, NOT a closure regression. Log + skip (don't fail).
			skipped++
			t.Logf("SKIP  %-46s [%s] %v", s.Name, s.Area, runErr)
			continue
		}
		ok, gotStr, wantStr := checkExpect(s, got)
		if ok {
			pass++
			continue
		}
		// Compiled + ran but produced the WRONG value → a real closure-capture bug.
		wrong++
		t.Errorf("CLOSURE BUG  %-40s [%s]\n    got=%s want=%s\n    why: %s",
			s.Name, s.Area, gotStr, wantStr, s.Rationale)
	}
	t.Logf("closure scenarios: %d/%d passed, %d wrong-result, %d skipped (unsupported syntax)",
		pass, len(scn), wrong, skipped)
	if wrong > 0 {
		t.Fatalf("%d scenario(s) returned the WRONG result — closure capture is broken for those cases", wrong)
	}
}

func checkExpect(s closureScenario, got value.Value) (ok bool, gotStr, wantStr string) {
	switch s.ExpectKind {
	case "number":
		gotStr = fmt.Sprintf("number(%v)", got.N)
		wantStr = fmt.Sprintf("number(%v)", s.ExpectNum)
		ok = got.K == value.Number && got.N == s.ExpectNum
	case "bool":
		gotStr = fmt.Sprintf("bool(%v)", got.N != 0)
		wantStr = fmt.Sprintf("bool(%v)", s.ExpectBool)
		ok = got.K == value.Bool && (got.N != 0) == s.ExpectBool
	case "string":
		gotStr = fmt.Sprintf("string(%v)", got.V)
		wantStr = fmt.Sprintf("string(%v)", s.ExpectStr)
		ok = got.K == value.String && got.V == s.ExpectStr
	default:
		gotStr, wantStr = fmt.Sprintf("%v", got.V), "?"
	}
	if got.K == value.Nil {
		gotStr = "nil (captured var was wiped)"
	}
	return ok, gotStr, wantStr
}
