#!/usr/bin/env python3
# Vendor script for jit animate: fetch the animate.css source (MIT, see ANIMATE_LICENSE) at a pinned
# version and generate animate_catalog_gen.go — one entry per animation with its @keyframes and the
# extra declarations its class rule carries. Run from anywhere:
#     python engine/jit/css/vendor_animate.py
#
# Naming: upstream camelCase → kebab utility name (fadeInUp → animate-fade-in-up). Two upstream names
# are Tailwind's (bounce, pulse) and Tailwind's meaning wins in jitcss, so they are skipped here.
import io, os, re, subprocess, tarfile, urllib.request

VERSION = "4.1.1"
URL = "https://registry.npmjs.org/animate.css/-/animate.css-%s.tgz" % VERSION
SKIP = {"bounce", "pulse"}  # Tailwind-owned names keep Tailwind's motion
GROUPS = [  # the animate.style sidebar order
    "attention_seekers", "back_entrances", "back_exits", "bouncing_entrances", "bouncing_exits",
    "fading_entrances", "fading_exits", "flippers", "lightspeed", "rotating_entrances", "rotating_exits",
    "specials", "zooming_entrances", "zooming_exits", "sliding_entrances", "sliding_exits",
]

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "animate_catalog_gen.go")
LICENSE = os.path.join(HERE, "ANIMATE_LICENSE")


def kebab(name):
    return re.sub(r"(?<=[a-z0-9])([A-Z])", r"-\1", name).lower()


def minify(css):
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    css = re.sub(r"\s+", " ", css)
    css = re.sub(r"\s*([{}:;,])\s*", r"\1", css)
    return css.replace(";}", "}").strip()


def block(css, start):
    """Return (body, end) for the {...} block whose opening brace is the first after `start`."""
    i = css.index("{", start)
    depth, j = 0, i
    for j in range(i, len(css)):
        if css[j] == "{":
            depth += 1
        elif css[j] == "}":
            depth -= 1
            if depth == 0:
                break
    return css[i + 1:j], j + 1


def parse(name, css):
    """One source file → (keyframes body, factor, extra declarations)."""
    m = re.search(r"@keyframes\s+" + name + r"\s*", css)
    assert m, "no @keyframes %s" % name
    frames, _ = block(css, m.end())
    rule = re.search(r"\n\.(?:animated\.)?" + name + r"\s*\{", css)
    assert rule, "no class rule for %s" % name
    body, _ = block(css, rule.start())
    factor, extra = "", []
    for decl in minify(body).split(";"):
        if not decl:
            continue
        prop, value = decl.split(":", 1)
        if prop == "animation-name":
            assert value == name, (name, value)
        elif prop == "animation-duration":
            f = re.fullmatch(r"calc\(var\(--animate-duration\)\s*\*\s*([0-9.]+)\)", value)
            assert f, (name, value)
            factor = f.group(1)
        else:
            extra.append(prop + ":" + value)
    return minify(frames), factor, ";".join(extra)


def goquote(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    data = urllib.request.urlopen(URL, timeout=60).read()
    tar = tarfile.open(fileobj=io.BytesIO(data), mode="r:gz")
    files = {m.name: tar.extractfile(m).read().decode("utf-8") for m in tar.getmembers() if m.isfile()}
    io.open(LICENSE, "w", encoding="utf-8", newline="\n").write(files["package/LICENSE"])

    groups, entries = [], {}
    for group in GROUPS:
        prefix = "package/source/%s/" % group
        names = []
        for path in sorted(p for p in files if p.startswith(prefix) and p.endswith(".css")):
            upstream = path[len(prefix):-4]
            if upstream in SKIP:
                continue
            name = kebab(upstream)
            assert name not in entries, name
            entries[name] = (group,) + parse(upstream, files[path])
            names.append(name)
        assert names, group
        groups.append((group, names))
    total = sum(len(n) for _, n in groups)

    w = io.StringIO()
    w.write("// Code generated by vendor_animate.py from animate.css v%s (MIT, see ANIMATE_LICENSE). DO NOT EDIT.\n\n" % VERSION)
    w.write("package css\n\n")
    w.write("const animateVendoredVersion = %s\n\n" % goquote(VERSION))
    w.write("// animateVendored is the animate.css library: %d animations, keyed by utility name.\n" % total)
    w.write("var animateVendored = map[string]animateEntry{\n")
    for name in sorted(entries):
        group, frames, factor, extra = entries[name]
        w.write("\t%s: {group: %s, frames: %s, factor: %s, extra: %s},\n" % (
            goquote(name), goquote(group), goquote("@keyframes animate--" + name + "{" + frames + "}"),
            goquote(factor), goquote(extra)))
    w.write("}\n\n")
    w.write("// animateVendoredGroups lists the upstream groups in animate.style's order with their utility\n")
    w.write("// names — the shape of a gallery page.\n")
    w.write("var animateVendoredGroups = []AnimationGroup{\n")
    for group, names in groups:
        w.write("\t{Name: %s, Animations: []string{%s}},\n" % (goquote(group), ", ".join(goquote(n) for n in names)))
    w.write("}\n")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(w.getvalue())
    subprocess.run(["gofmt", "-w", OUT], check=True)
    print("animate.css v%s: %d animations in %d groups -> %s" % (VERSION, total, len(groups), os.path.relpath(OUT)))


if __name__ == "__main__":
    main()
