package sql

import (
	"math"
	"testing"
)

func TestSequenceSyntax(t *testing.T) {
	for _, query := range []string{
		`CREATE SEQUENCE orders`,
		`CREATE SEQUENCE public.orders AS BIGINT START WITH 5 INCREMENT BY 2 MINVALUE 1 MAXVALUE 9 CYCLE CACHE 4096 OWNED BY NONE`,
		`CREATE SEQUENCE IF NOT EXISTS orders INCREMENT -1 NO MINVALUE NO MAXVALUE NO CYCLE`,
		`CREATE TABLE cached_identity (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 32) PRIMARY KEY)`,
		`DROP SEQUENCE IF EXISTS public.orders RESTRICT`,
		`ALTER SEQUENCE public.orders RESTART`,
		`ALTER SEQUENCE IF EXISTS orders RESTART WITH -9223372036854775808`,
	} {
		if _, err := ParseStatement(query); err != nil {
			t.Fatalf("%s: %v", query, err)
		}
	}
	statement, _ := ParseStatement(`CREATE SEQUENCE descending INCREMENT -1`)
	if p := statement.CreateSequence; p.Start != -1 || p.Minimum != math.MinInt64 || p.Maximum != -1 {
		t.Fatal(p)
	}
	statement, _ = ParseStatement(`CREATE SEQUENCE cached CACHE 128`)
	if statement.CreateSequence.Cache != 128 {
		t.Fatalf("cache = %d", statement.CreateSequence.Cache)
	}
	statement, _ = ParseStatement(`CREATE TABLE cached_identity (id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 32) PRIMARY KEY)`)
	if got := statement.CreateTable.Columns[0].SequenceCache; got != 32 {
		t.Fatalf("identity cache = %d", got)
	}
	for _, query := range []string{
		`CREATE SEQUENCE s INCREMENT 0`, `CREATE SEQUENCE s MINVALUE 3 MAXVALUE 3`,
		`CREATE SEQUENCE s CACHE 0`, `CREATE SEQUENCE s CACHE 4097`, `CREATE SEQUENCE s CACHE -2`,
		`CREATE SEQUENCE s START 9223372036854775808`,
		`CREATE SEQUENCE s START 2 START 3`, `CREATE SEQUENCE s NO START 3`,
		`CREATE SEQUENCE s OWNED BY orders.id`, `CREATE SEQUENCE other.s`,
		`CREATE SEQUENCE s AS INT`, `CREATE OR REPLACE SEQUENCE s`,
		`ALTER SEQUENCE s RESTART WITH`, `ALTER SEQUENCE s INCREMENT 2`, `DROP SEQUENCE s CASCADE`,
		`CREATE TABLE bad (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 0))`,
		`CREATE TABLE bad (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 4097))`,
		`CREATE TABLE bad (id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 2))`,
	} {
		if _, err := ParseStatement(query); err == nil {
			t.Fatalf("accepted %s", query)
		}
	}
}
